software-mansion/TypeGPU

apps/typegpu-docs/src/content/docs/guides/getting-started.mdx
=> Troubleshooting section in Getting Started guide

apps/typegpu-docs/src/components/FeatureCard.astro, apps/typegpu-docs/src/pages/index.astro
=> docs: Linking to react-native-wgpu on the landing page.

packages/typegpu/src/createRuntime.ts, packages/typegpu/src/tgpuBufferUtils.ts
=> Fix write size 

apps/typegpu-docs/src/components/ExampleView.tsx, apps/typegpu-docs/src/content/examples/simple/gradient-tiles-typedbuffers.ts, apps/typegpu-docs/src/utils/examples/exampleRunner.ts
so far it works (i think), but isn't pretty
=> Control button definitions via comments + phase 1 gradient tiles variant

apps/typegpu-docs/astro.config.mjs, apps/typegpu-docs/src/components/GetStartedButton.astro, apps/typegpu-docs/src/components/design/Button.tsx, apps/typegpu-docs/src/components/design/Table.tsx, apps/typegpu-docs/src/pages/index.astro
=> Bring back link to examples + some small visual adjustments

LICENSE.md
=> Rename license file

apps/typegpu-docs/src/components/CodeEditor.tsx, apps/typegpu-docs/src/utils/examples/exampleRunner.ts
=> Hide experimental in editor when importing `typegpu`

apps/typegpu-docs/src/assets/hamburger.svg, apps/typegpu-docs/src/components/CodeEditor.tsx, apps/typegpu-docs/src/components/ControlPanel.tsx, apps/typegpu-docs/src/components/ExampleLayout.tsx, apps/typegpu-docs/src/components/ExampleLink.tsx, apps/typegpu-docs/src/components/ExampleView.tsx, apps/typegpu-docs/src/utils/examples/codeEditorShownAtom.ts, apps/typegpu-docs/src/utils/examples/menuShownAtom.ts
=> Make examples page mobile friendly

packages/tgpu-cli/colors.mjs, packages/tgpu-cli/gen.mjs, packages/tgpu-cli/package.json, packages/tgpu-cli/tgpu-cli.mjs, pnpm-lock.yaml
=> POC of a companion CLI for TypeGPU

packages/typegpu/src/data/numeric.ts, packages/typegpu/src/tgpuBufferUsage.ts, packages/typegpu/src/tgpuTexture.ts, packages/typegpu/tests/primitiveCast.test.ts
=> Callable primitives

apps/typegpu-docs/src/content/examples/simulation/boids-typedbuffers.ts
=> Added a boids preset

packages/typegpu/src/resolutionCtx.ts, packages/typegpu/tests/indentController.test.ts
=> Fix IndentController for big indentation levels

packages/tgpu-cli/gen.mjs, packages/tgpu-cli/tests/bindGroupLayouts.test.ts, packages/tgpu-cli/tests/structs.test.ts
=> BindGroupLayout cli generator

packages/typegpu/src/data/align.ts, packages/typegpu/src/data/array.ts, packages/typegpu/src/types.ts
=> Make loose data unresolvable

packages/typegpu/src/data/array.ts
=> Document TgpuArray objects and types via comments

packages/tgpu-cli/package.json, packages/tgpu-cli/tgpu-cli.mjs, pnpm-lock.yaml
Adds:
- Watch mode for cli
- Allows for input to be positional
- Provides a way to print help for gen command
- Provides error file and line info (if available)
closes #393
=> Added watch mode to cli

apps/typegpu-docs/astro.config.mjs, apps/typegpu-docs/src/content/docs/guides/generating-js-from-wgsl.mdx, apps/typegpu-docs/src/content/docs/guides/roots.mdx, apps/typegpu-docs/src/content/docs/tutorials/triangle-to-boids/code/step1-typegpu.ts, apps/typegpu-docs/src/content/docs/tutorials/triangle-to-boids/code/step1side-typegpu.ts, apps/typegpu-docs/src/content/docs/tutorials/triangle-to-boids/code/step2-typegpu.ts, apps/typegpu-docs/src/content/docs/tutorials/triangle-to-boids/code/step3-typegpu.ts, apps/typegpu-docs/src/content/docs/tutorials/triangle-to-boids/code/step4-typegpu.ts, apps/typegpu-docs/src/content/docs/tutorials/triangle-to-boids/code/step5-typegpu.ts, apps/typegpu-docs/src/content/docs/tutorials/triangle-to-boids/code/step6-typegpu.ts, apps/typegpu-docs/src/content/docs/tutorials/triangle-to-boids/code/step7-typegpu.ts, apps/typegpu-docs/src/content/docs/tutorials/triangle-to-boids/code/step8-typegpu.ts, apps/typegpu-docs/src/content/docs/tutorials/triangle-to-boids/code/step9-typegpu.ts, apps/typegpu-docs/src/content/docs/tutorials/triangle-to-boids/index.mdx
- Skipping type-checking of the tutorial code snippets (for now).
- Showing draft posts only in DEV.
=> Cleaning up the docs a bit

packages/typegpu/src/bindGroupResolver.ts, packages/typegpu/src/createRoot.ts, packages/typegpu/src/experimental/index.ts, packages/typegpu/src/programBuilder.ts, packages/typegpu/src/tgpuBuffer.ts, packages/typegpu/src/tgpuPlum.ts, packages/typegpu/src/tgpuPlumTypes.ts, packages/typegpu/src/tgpuRoot.ts, packages/typegpu/tests/bindGroupLayout.test.ts
=> Rename runtime to root.

packages/typegpu/src/data/atomic.ts
=> Document Atomic types and objects via comments

packages/typegpu/src/data/vector.ts
=> Document vector types and objects via comments

packages/typegpu/src/data/matrix.ts
=> Document matrix types and objects via comments

packages/tgpu-cli/tgpu-cli.mjs
=> Remove `--input` option from `tgpu-cli` gen

packages/tgpu-cli/gen.mjs, packages/tgpu-cli/tgpu-cli.mjs
=> Fix overriding files in tgpu-cli with watch mode and --keep option

packages/typegpu/src/data/numeric.ts
=> Add docs for numerics.

packages/typegpu/src/tgpuBindGroupLayout.ts, packages/typegpu/tests/bindGroupLayout.test.ts
=> Hide `bound` from public API

apps/typegpu-docs/src/content/examples/simple/increment-tgsl.ts
should fix docs not building on main
=> Fix unstable increment example

apps/typegpu-docs/src/content/docs/guides/tgpu-buffer-api.mdx
=> docs: Update Typed Buffers guide to use new root API

packages/tgpu-gen/gen.mjs, packages/tgpu-gen/package.json, packages/tgpu-gen/tests/functions.test.ts, pnpm-lock.yaml
=> Function support in tgpu-gen

apps/typegpu-docs/src/components/ExamplePage.tsx, apps/typegpu-docs/src/content/docs/tutorials/triangle-to-boids/code/step1-webgpu.ts, apps/typegpu-docs/src/content/docs/tutorials/triangle-to-boids/code/step2-webgpu.ts, apps/typegpu-docs/src/content/docs/tutorials/triangle-to-boids/code/step4-webgpu.ts, apps/typegpu-docs/src/content/docs/tutorials/triangle-to-boids/code/step5-webgpu.ts, apps/typegpu-docs/src/content/docs/tutorials/triangle-to-boids/code/step9-webgpu.ts
references #490 
\+ fixed one warning while at it
=> Fix deployment after removing addElement toolkit api

apps/typegpu-docs/src/content/docs/tutorials/triangle-to-boids/index.mdx, apps/typegpu-docs/src/content/examples/simulation/fluid-double-buffering/index.ts, packages/rollup-plugin/src/index.ts, packages/tgpu-gen/gen.mjs, packages/tgpu-gen/tests/functions.test.ts, packages/tgsl-tools/README.md, packages/typegpu/src/core/function/tgpuComputeFn.ts, packages/typegpu/src/core/function/tgpuFn.ts, packages/typegpu/src/core/function/tgpuFragmentFn.ts, packages/typegpu/src/core/function/tgpuVertexFn.ts, packages/typegpu/tests/function.test.ts, packages/typegpu/tests/rawFn.test.ts, packages/typegpu/tests/tgslFn.test.ts
=> Rename implement to does in tgpu.fn

apps/typegpu-docs/src/components/ExampleView.tsx, apps/typegpu-docs/src/content/examples/algorithms/mnist-inference/index.html, apps/typegpu-docs/src/content/examples/algorithms/mnist-inference/index.ts
=> Add loading and draw here UI elements to the MNIST example

apps/typegpu-docs/src/components/ControlPanel.tsx, apps/typegpu-docs/src/components/ExampleLayout.tsx, apps/typegpu-docs/src/content/examples/rendering/box-raytracing/index.ts, packages/typegpu/src/core/function/externals.ts, packages/typegpu/src/core/resolve/tgpuResolve.ts, packages/typegpu/src/data/vector.ts
=> Update Box Raytracing example to use `tgpu.resolve` API

apps/typegpu-docs/src/content/examples/rendering/box-raytracing/index.ts
=> Fix box raytracing example after fn api changes

apps/typegpu-docs/src/content/examples/simulation/confetti/index.html, apps/typegpu-docs/src/content/examples/simulation/confetti/index.ts, apps/typegpu-docs/src/content/examples/simulation/confetti/meta.json
=> Confetti example

apps/typegpu-docs/astro.config.mjs, apps/typegpu-docs/src/content/docs/fundamentals/slots.mdx
This is far from a complete docs page, but will allow us to iterate on the examples and think of good use-case examples to showcase its power.
=> docs: A draft of the slots API docs.

packages/tgpu-gen/tests/structs.test.ts, packages/typegpu/src/tgpuBindGroupLayout.ts, packages/typegpu/tests/bindGroupLayout.test.ts
=> Disallow runtime-sized data in uniforms

apps/typegpu-docs/src/content/docs/fundamentals/roots.mdx, apps/typegpu-docs/src/content/examples/algorithms/matrix-multiplication/index.ts, apps/typegpu-docs/src/content/examples/algorithms/mnist-inference/index.ts, apps/typegpu-docs/src/content/examples/image-processing/blur/index.ts, apps/typegpu-docs/src/content/examples/image-processing/camera-thresholding/index.ts, apps/typegpu-docs/src/content/examples/rendering/box-raytracing/index.ts, apps/typegpu-docs/src/content/examples/simple/gradient-tiles/index.ts, apps/typegpu-docs/src/content/examples/simple/increment-tgsl/index.ts, apps/typegpu-docs/src/content/examples/simple/increment/index.ts, apps/typegpu-docs/src/content/examples/simulation/boids-experimental/index.ts, apps/typegpu-docs/src/content/examples/simulation/boids-next/index.ts, apps/typegpu-docs/src/content/examples/simulation/boids/index.ts, apps/typegpu-docs/src/content/examples/simulation/confetti/index.ts, apps/typegpu-docs/src/content/examples/simulation/fluid-double-buffering/index.ts, apps/typegpu-docs/src/content/examples/simulation/fluid-with-atomics/index.ts, packages/typegpu/src/core/root/init.ts
=> Destroy gpu device on root.destroy

apps/typegpu-docs/src/content/examples/simulation/confetti/index.ts, packages/typegpu/src/core/buffer/buffer.ts, packages/typegpu/src/core/pipeline/computePipeline.ts, packages/typegpu/src/core/pipeline/renderPipeline.ts, packages/typegpu/src/core/texture/texture.ts, packages/typegpu/src/tgpuBindGroupLayout.ts, packages/typegpu/tests/bindGroupLayout.test.ts, packages/typegpu/tests/runtime.test.ts, packages/typegpu/tests/unmanagedIO.test.ts
=> Improve labeling gpu objects

apps/typegpu-docs/src/content/docs/integration/working-with-wgpu-matrix.mdx, apps/typegpu-docs/src/content/examples/algorithms/matrix-multiplication/index.ts, apps/typegpu-docs/src/content/examples/image-processing/blur/index.ts, apps/typegpu-docs/src/content/examples/image-processing/camera-thresholding/index.ts, apps/typegpu-docs/src/content/examples/image-processing/chroma-keying/index.ts, apps/typegpu-docs/src/content/examples/rendering/box-raytracing/index.ts, apps/typegpu-docs/src/content/examples/simple/gradient-tiles/index.ts, apps/typegpu-docs/src/content/examples/simple/increment-tgsl/index.ts, apps/typegpu-docs/src/content/examples/simple/increment/index.ts, apps/typegpu-docs/src/content/examples/simulation/boids-experimental/index.ts, apps/typegpu-docs/src/content/examples/simulation/boids-next/index.ts, apps/typegpu-docs/src/content/examples/simulation/boids/index.ts, apps/typegpu-docs/src/content/examples/simulation/confetti/index.ts, apps/typegpu-docs/src/content/examples/simulation/fluid-double-buffering/index.ts, apps/typegpu-docs/src/content/examples/simulation/fluid-with-atomics/index.ts, apps/typegpu-docs/src/content/examples/simulation/game-of-life/index.ts, apps/typegpu-docs/src/utils/examples/exampleRunner.ts
=> Allow for `* as d` wildcard imports in example code

packages/typegpu/src/core/buffer/buffer.ts, packages/typegpu/tests/buffer.test.ts, packages/typegpu/tests/bufferUsage.test.ts
=> Allow only vertex usage for buffers containing loose data

packages/typegpu/src/core/function/fnCore.ts
=> Make plugin not override anything passed in $uses

apps/typegpu-docs/src/content/examples/algorithms/matrix-multiplication/index.ts, apps/typegpu-docs/src/content/examples/algorithms/matrix-multiplication/meta.json, apps/typegpu-docs/src/content/examples/image-processing/blur/index.ts, apps/typegpu-docs/src/content/examples/image-processing/blur/meta.json, apps/typegpu-docs/src/content/examples/image-processing/camera-thresholding/index.ts, apps/typegpu-docs/src/content/examples/image-processing/camera-thresholding/meta.json, apps/typegpu-docs/src/content/examples/image-processing/chroma-keying/index.ts, apps/typegpu-docs/src/content/examples/image-processing/chroma-keying/meta.json
=> Make some examples public for 0.3

apps/typegpu-docs/src/content/examples/rendering/box-raytracing/index.ts, packages/typegpu/src/core/function/tgpuFn.ts, packages/typegpu/src/core/root/init.ts, packages/typegpu/src/core/root/rootTypes.ts, packages/typegpu/src/core/slot/accessor.ts, packages/typegpu/src/core/slot/slotTypes.ts, packages/typegpu/src/experimental/index.ts, packages/typegpu/tests/accessor.test.ts
=> Create `tgpu.accessor` API

packages/typegpu/src/core/texture/texture.ts, packages/typegpu/src/tgpuBindGroupLayout.ts, packages/typegpu/tests/texture.test.ts
=> Change how texture views are created.

packages/typegpu/src/core/buffer/buffer.ts
=> Improve the behavior of `$addFlags`

apps/typegpu-docs/src/content/docs/integration/webgpu-interoperability.mdx, apps/typegpu-docs/src/content/examples/algorithms/matrix-multiplication/index.ts, apps/typegpu-docs/src/content/examples/image-processing/blur/index.ts, apps/typegpu-docs/src/content/examples/image-processing/camera-thresholding/index.ts, apps/typegpu-docs/src/content/examples/image-processing/chroma-keying/index.ts, packages/typegpu/src/core/resolve/tgpuResolve.ts, packages/typegpu/tests/accessor.test.ts, packages/typegpu/tests/align.test.ts, packages/typegpu/tests/bindGroupLayout.test.ts, packages/typegpu/tests/constant.test.ts, packages/typegpu/tests/declare.test.ts, packages/typegpu/tests/derived.test.ts, packages/typegpu/tests/function.test.ts, packages/typegpu/tests/rawFn.test.ts, packages/typegpu/tests/resolve.test.ts, packages/typegpu/tests/slot.test.ts, packages/typegpu/tests/texture.test.ts, packages/typegpu/tests/tgslFn.test.ts, packages/typegpu/tests/utils/parseResolved.ts, packages/typegpu/tests/variable.test.ts
=> Change resolve api

packages/rollup-plugin/package.json, packages/tgpu-jit/package.json, packages/tinyest-for-wgsl/package.json, packages/tinyest-for-wgsl/src/parsers.ts, packages/tinyest/package.json, packages/tinyest/src/nodes.ts, packages/typegpu/package.json, packages/typegpu/src/core/pipeline/connectAttachmentToShader.ts, packages/typegpu/src/data/index.ts, packages/typegpu/src/errors.ts, packages/typegpu/src/experimental/index.ts, packages/typegpu/src/smol/wgslGenerator.ts, packages/typegpu/tests/derived.test.ts, pnpm-lock.yaml
The way of handling order of operations in this PR is a bit eager, causing every binary expression to be surrounded by parentheses, but it... works for now 🤷
=> feat: Handling unary operators & order of binary operators better.

packages/typegpu/src/core/constant/tgpuConstant.ts, packages/typegpu/src/core/declare/tgpuDeclare.ts, packages/typegpu/src/core/function/tgpuComputeFn.ts, packages/typegpu/src/core/function/tgpuFn.ts, packages/typegpu/src/core/function/tgpuFragmentFn.ts, packages/typegpu/src/core/function/tgpuVertexFn.ts, packages/typegpu/src/core/pipeline/computePipeline.ts, packages/typegpu/src/core/pipeline/renderPipeline.ts, packages/typegpu/src/core/resolve/tgpuResolve.ts, packages/typegpu/src/core/sampler/sampler.ts, packages/typegpu/src/core/texture/externalTexture.ts, packages/typegpu/src/core/texture/texture.ts, packages/typegpu/src/core/variable/tgpuVariable.ts, packages/typegpu/src/data/array.ts, packages/typegpu/src/data/struct.ts, packages/typegpu/src/data/vector.ts, packages/typegpu/src/types.ts
=> fix: Add missing toString methods to TgpuResolvables

apps/typegpu-docs/src/content/docs/integration/webgpu-interoperability.mdx, apps/typegpu-docs/src/content/examples/image-processing/blur/meta.json, packages/typegpu/src/core/root/rootTypes.ts, packages/typegpu/src/index.ts
=> Hide textures in 0.3

apps/typegpu-docs/src/components/ExamplePage.tsx, apps/typegpu-docs/src/components/ExampleView.tsx, apps/typegpu-docs/src/components/stackblitz/stackBlitzIndex.ts, apps/typegpu-docs/src/content/examples/algorithms/matrix-multiplication/index.html, apps/typegpu-docs/src/content/examples/image-processing/camera-thresholding/index.html, apps/typegpu-docs/src/content/examples/image-processing/chroma-keying/index.html, apps/typegpu-docs/src/content/examples/image-processing/chroma-keying/index.ts, apps/typegpu-docs/src/layouts/PageLayout.astro
=> fix: 0.3 live examples mobile layout

apps/typegpu-docs/src/content/docs/reference/data-schema-cheatsheet.mdx
=> docs: Add f16 vector types to cheatsheet

packages/typegpu/src/core/resolve/externals.ts, packages/typegpu/tests/rawFn.test.ts
=> Fix replacing object access identifiers in replaceExternalsInWgsl

packages/typegpu/src/core/root/rootTypes.ts
=> Add missing jsdocs to the TgpuRoot type

packages/typegpu/src/experimental/index.ts, packages/typegpu/src/index.ts, packages/typegpu/src/tgpuBindGroupLayout.ts, packages/typegpu/tests/bindGroupLayout.test.ts
=> Fix invalid bound type for samplers

apps/typegpu-docs/src/components/ExampleLayout.tsx, apps/typegpu-docs/src/content/examples/image-processing/camera-thresholding/meta.json, apps/typegpu-docs/src/content/examples/image-processing/chroma-keying/meta.json, apps/typegpu-docs/src/utils/examples/exampleContent.ts
=> Hide camera examples on iOS Safari for now

apps/typegpu-docs/src/components/ExampleLayout.tsx, apps/typegpu-docs/src/components/ExampleLink.tsx, apps/typegpu-docs/src/components/ExampleList.tsx
=> docs: Add toggle to show experimental examples

packages/typegpu/src/data/matrix.ts, packages/typegpu/src/data/vectorOps.ts, packages/typegpu/src/std/numeric.ts
closes #787 
multiplication of a vector and a matrix is not yet supported
=> Matrix multiplication in typegpu/std

apps/typegpu-docs/src/content/examples/rendering/box-raytracing/index.ts, apps/typegpu-docs/src/content/examples/simple/increment-tgsl/index.ts, apps/typegpu-docs/src/content/examples/simulation/boids-next/index.ts, apps/typegpu-docs/src/content/examples/simulation/confetti/index.ts, apps/typegpu-docs/src/content/examples/simulation/fluid-double-buffering/index.ts, apps/typegpu-docs/src/content/examples/simulation/fluid-with-atomics/index.ts, packages/typegpu/src/core/buffer/buffer.ts, packages/typegpu/src/core/buffer/bufferUsage.ts, packages/typegpu/src/core/root/init.ts, packages/typegpu/src/core/root/rootTypes.ts, packages/typegpu/src/index.ts, packages/typegpu/src/tgpuBindGroupLayout.ts, packages/typegpu/tests/accessor.test.ts, packages/typegpu/tests/asUsage.test.ts, packages/typegpu/tests/bufferUsage.test.ts, packages/typegpu/tests/derived.test.ts, packages/typegpu/tests/root.test.ts, packages/typegpu/tests/slot.test.ts
closes #828 
closes #694 
closes #693
=> Replace as*() functions with .as(*) for buffer usages

apps/typegpu-docs/src/content/examples/rendering/box-raytracing/index.ts, apps/typegpu-docs/src/content/examples/simple/increment-tgsl/index.ts, apps/typegpu-docs/src/content/examples/simulation/boids-next/index.ts, apps/typegpu-docs/src/content/examples/simulation/confetti/index.ts, apps/typegpu-docs/src/content/examples/simulation/fluid-double-buffering/index.ts, apps/typegpu-docs/src/content/examples/simulation/fluid-with-atomics/index.ts, packages/typegpu/src/builtin.ts, packages/typegpu/src/core/function/fnTypes.ts, packages/typegpu/src/core/function/tgpuComputeFn.ts, packages/typegpu/src/core/function/tgpuFragmentFn.ts, packages/typegpu/src/core/function/tgpuVertexFn.ts, packages/typegpu/src/core/root/rootTypes.ts, packages/typegpu/src/data/attributes.ts, packages/typegpu/tests/computePipeline.test.ts, packages/typegpu/tests/rawFn.test.ts, packages/typegpu/tests/renderPipeline.test.ts, packages/typegpu/tests/resolve.test.ts, packages/typegpu/tests/tgslFn.test.ts
=> impr: Update entry function parameters

.github/workflows/pkg-pr.yml, apps/typegpu-docs/src/pages/benchmark/modules.ts, apps/typegpu-docs/src/pages/benchmark/parameter-set-row.tsx, apps/typegpu-docs/src/pages/benchmark/parameter-set.ts, package.json, pnpm-lock.yaml
=> chore: Allow PR-builds to be compared with other versions in the benchmark app

apps/typegpu-docs/src/content/examples/simulation/fluid-double-buffering/index.ts, packages/tgpu-wgsl-parser/src/grammar.ne, packages/tgpu-wgsl-parser/src/grammar.ts, packages/tinyest-for-wgsl/src/parsers.ts, packages/tinyest/src/nodes.ts, packages/typegpu/src/smol/wgslGenerator.ts, packages/typegpu/src/std/atomic.ts, packages/typegpu/src/std/index.ts, packages/typegpu/tests/smol/wgslGenerator.test.ts
=> feat: Add support for `For` and `While` statements in TGSL

packages/typegpu/src/gpuMode.ts, packages/typegpu/src/resolutionCtx.ts
=> impr: Change `GPUMode` to check stack instead of context

packages/tinyest-for-wgsl/package.json, packages/tinyest-for-wgsl/src/parsers.ts, packages/unplugin-typegpu/package.json, pnpm-lock.yaml
=> fix: Make babel plugin work with boolean and string literals

.github/workflows/ci.yml
previously biome check didn't run for PRs to the release branch
=> dx: Run CI on any PR, not only to main

packages/tinyest-for-wgsl/package.json, packages/tinyest-for-wgsl/tests/parsers.test.ts, packages/typegpu/vitest.config.mts, packages/unplugin-typegpu/package.json, packages/unplugin-typegpu/src/babel.ts, packages/unplugin-typegpu/src/common.ts, packages/unplugin-typegpu/src/index.ts, packages/unplugin-typegpu/test/aliasing.test.ts, packages/unplugin-typegpu/test/parser-options.test.ts, packages/unplugin-typegpu/test/tgsl-transpiling.test.ts, packages/unplugin-typegpu/test/transform.ts, pnpm-lock.yaml
=> test: Create e2e test suite for `unplugin-typegpu`

apps/typegpu-docs/src/components/CodeEditor.tsx, apps/typegpu-docs/src/components/ExampleView.tsx, apps/typegpu-docs/src/layouts/PageLayout.astro
=> docs: Improve code editor UI

packages/typegpu/src/tgpuBindGroupLayout.ts, packages/typegpu/tests/bindGroupLayout.test.ts
=> fix: Allow input of tgpu texture views and samplers to bind groups

.github/workflows/pkg-pr.yml
=> dx: Don't run pkg-pr workflow on PRs from forks

packages/typegpu/src/data/compiledIO.ts
without this fluid with atomics example doesn't work (on release too ;_;)
=> fix: Fix compiled io writer for atomics

apps/typegpu-docs/src/content/examples/simulation/fluid-double-buffering/index.ts, packages/tinyest-for-wgsl/src/parsers.ts, packages/tinyest/src/nodes.ts, packages/typegpu/package.json, packages/typegpu/src/smol/wgslGenerator.ts, packages/typegpu/tests/accessor.test.ts, packages/typegpu/tests/bindGroupLayout.test.ts, packages/typegpu/tests/bufferUsage.test.ts, packages/typegpu/tests/constant.test.ts, packages/typegpu/tests/declare.test.ts, packages/typegpu/tests/derived.test.ts, packages/typegpu/tests/function.test.ts, packages/typegpu/tests/rawFn.test.ts, packages/typegpu/tests/resolve.test.ts, packages/typegpu/tests/slot.test.ts, packages/typegpu/tests/smol/wgslGenerator.test.ts, packages/typegpu/tests/tgslFn.test.ts, packages/typegpu/tests/utils/parseResolved.ts, packages/typegpu/tests/variable.test.ts, packages/typegpu/tests/vector.test.ts, packages/typegpu/vitest.config.mts, pnpm-lock.yaml
=> feat: Handle `ArrayExpression` in TGSL and switch to WESL parser

packages/typegpu/src/core/function/tgpuComputeFn.ts, packages/typegpu/src/core/function/tgpuFn.ts, packages/typegpu/src/core/function/tgpuFragmentFn.ts, packages/typegpu/src/core/function/tgpuVertexFn.ts, packages/unplugin-typegpu/src/common.ts, packages/unplugin-typegpu/test/tgsl-transpiling-with-does.test.ts
=> Restore `does` method on fn shells for backwards compatibility

packages/tinyest-for-wgsl/src/parsers.ts, packages/typegpu-noise/src/random.ts
=> fix: randSeed functions in typegpu/noise

apps/typegpu-docs/src/pages/benchmark/suites.ts, apps/typegpu-docs/src/pages/benchmark/test-suites/vector-creation.ts, packages/typegpu/tsup.config.ts
=> feat: Add a benchmark suite for vector creation

README.md, apps/typegpu-docs/src/content/examples/image-processing/camera-thresholding/index.html, apps/typegpu-docs/src/content/examples/image-processing/chroma-keying-next/index.html, apps/typegpu-docs/src/content/examples/image-processing/chroma-keying/index.html, apps/typegpu-docs/src/pages/index.astro, packages/typegpu/README.md
=> fix: Add `playsinline` attribute to video elements

apps/typegpu-docs/src/content/examples/rendering/3d-fish/compute.ts, apps/typegpu-docs/src/content/examples/rendering/3d-fish/render.ts, apps/typegpu-docs/src/content/examples/rendering/3d-fish/tgsl-helpers.ts, apps/typegpu-docs/src/content/examples/rendering/box-raytracing/index.ts, apps/typegpu-docs/src/content/examples/simple/triangle/index.ts, apps/typegpu-docs/src/content/examples/simulation/boids-next/index.ts, apps/typegpu-docs/src/content/examples/simulation/confetti/index.ts, apps/typegpu-docs/src/content/examples/simulation/fluid-with-atomics/index.ts, packages/tgpu-jit/src/index.ts, packages/tinyest-for-wgsl/src/parsers.ts, packages/tinyest-for-wgsl/tests/parsers.test.ts, packages/tinyest/src/nodes.ts, packages/typegpu/src/core/function/astUtils.ts, packages/typegpu/src/core/function/fnCore.ts, packages/typegpu/src/core/function/fnTypes.ts, packages/typegpu/src/core/function/tgpuFn.ts, packages/typegpu/src/resolutionCtx.ts, packages/typegpu/src/types.ts, packages/typegpu/tests/rawFn.test.ts, packages/typegpu/tests/smol/wgslGenerator.test.ts, packages/typegpu/tests/tgpuFnRecordArgs.test.ts, packages/unplugin-typegpu/test/aliasing.test.ts, packages/unplugin-typegpu/test/kernel-directive.test.ts, packages/unplugin-typegpu/test/parser-options.test.ts, packages/unplugin-typegpu/test/tgsl-transpiling-with-does.test.ts, packages/unplugin-typegpu/test/tgsl-transpiling.test.ts
=> feat: Record argTypes in tgpuFn

packages/typegpu/src/data/unstruct.ts, packages/typegpu/src/data/wgslTypes.ts
I think that is the only one? I thought there were more but could not find them. If someones encounters one we could reopen the ticket
closes #1026
=> fix: Apply missing Prettify calls

packages/tgpu-gen/gen.mjs, packages/tgpu-gen/package.json, packages/tgpu-gen/tests/functions.test.ts, packages/tgpu-gen/tgpu-gen.mjs, packages/tgpu-gen/tsconfig.json, packages/unplugin-typegpu/test/kernel-and-js-directive.test.ts, packages/unplugin-typegpu/test/kernel-directive.test.ts, pnpm-lock.yaml
closes #678 
\+ fix TypeScript errors in the package
=> Update `tgpu-gen` to generate the latest function API, skip non-entry

apps/typegpu-docs/src/components/ExampleView.tsx
=> fix: Example max height with code editor shown

apps/typegpu-docs/astro.config.mjs, apps/typegpu-docs/src/components/stackblitz/openInStackBlitz.ts, apps/typegpu-docs/src/content/docs/tooling/unplugin-typegpu.mdx, packages/unplugin-typegpu/README.md
=> docs: unplugin-typegpu guide

packages/typegpu-noise/src/random.ts
=> Reuse sign and sqrt in typegpu-noise

packages/typegpu/src/tgsl/wgslGenerator.ts, packages/typegpu/tests/tgsl/wgslGenerator.test.ts
=> fix: Handle single-line statements in TGSL if/for/while

packages/typegpu/src/core/slot/derived.ts, packages/typegpu/tests/derived.test.ts, packages/typegpu/tests/tgsl/wgslGenerator.test.ts
=> impr: Throw error when trying to define tgpu.derived during resolution

packages/typegpu/src/data/wgslTypes.ts, packages/typegpu/tests/utilityTypes.test.ts
@iwoplaza please let me know if this suffices.
=> feat: Add `ExtractTypeLabel` type

apps/typegpu-docs/src/components/ControlPanel.tsx, apps/typegpu-docs/src/components/ExampleLayout.tsx, apps/typegpu-docs/src/components/ExampleLink.tsx, apps/typegpu-docs/src/components/ExampleList.tsx, apps/typegpu-docs/src/components/ExampleNotFound.tsx, apps/typegpu-docs/src/components/ExamplePage.tsx, apps/typegpu-docs/src/components/ExampleView.tsx, apps/typegpu-docs/src/components/design/Button.tsx, apps/typegpu-docs/src/components/design/ColorPicker.tsx, apps/typegpu-docs/src/components/design/DeleteIcon.tsx, apps/typegpu-docs/src/components/design/Select.tsx, apps/typegpu-docs/src/components/design/Slider.tsx, apps/typegpu-docs/src/components/design/Snackbar.tsx, apps/typegpu-docs/src/components/design/TextArea.tsx, apps/typegpu-docs/src/components/design/Toggle.tsx, apps/typegpu-docs/src/components/design/VectorSlider.tsx, apps/typegpu-docs/src/pages/benchmark/benchmark-app.tsx, apps/typegpu-docs/src/pages/benchmark/components/benchmark-results.tsx, apps/typegpu-docs/src/pages/benchmark/components/checkbox-tree.tsx, apps/typegpu-docs/src/pages/benchmark/components/parameter-set-row.tsx, biome.json
Feel free to ignore this PR, just thought you might want to enable this rule https://biomejs.dev/linter/rules/use-sorted-classes/
Note: this should be merged after #1286 or re-ran on main.
=> chore: Biome useSortedClasses for consistency and better compression

apps/typegpu-docs/src/content/examples/image-processing/camera-thresholding/index.html, apps/typegpu-docs/src/content/examples/image-processing/camera-thresholding/index.ts, apps/typegpu-docs/src/content/examples/rendering/3d-fish/index.html, apps/typegpu-docs/src/content/examples/rendering/3d-fish/index.ts, apps/typegpu-docs/src/layouts/loadingSpinner.css
=> docs: Add spinner to the Camera Thresholding example

apps/typegpu-docs/src/components/ExampleView.tsx, apps/typegpu-docs/src/content/examples/image-processing/blur/index.ts, apps/typegpu-docs/src/content/examples/simple/triangle/index.ts
=> docs: Fix control panel height on mobile

apps/typegpu-docs/src/content/examples/rendering/3d-fish/index.ts, apps/typegpu-docs/src/content/examples/rendering/function-visualizer/index.ts
=> fix: Page scroll on touch events in examples

apps/typegpu-docs/src/components/ExampleNotFound.tsx
=> docs: Improve "Example not found" UI

apps/typegpu-docs/src/content/examples/rendering/function-visualizer/index.html, apps/typegpu-docs/src/content/examples/rendering/function-visualizer/index.ts
=> docs: Make function visualizer canvas fit to container

apps/typegpu-docs/src/components/SearchableExampleList.tsx
closes #1363 
matches starlight's implementation
=> docs: Focus example search input on cmd/ctrl + k

apps/typegpu-docs/src/content/examples/rendering/perlin-noise/index.ts, packages/typegpu-noise/src/perlin-3d/dynamic-cache.ts, packages/typegpu/src/core/root/init.ts, packages/typegpu/src/core/root/rootTypes.ts, packages/typegpu/src/index.ts
=> feat: Pipelines `.pipe`

packages/typegpu/src/builtin.ts, packages/typegpu/src/data/attributes.ts, packages/typegpu/src/data/dataTypes.ts, packages/typegpu/src/data/index.ts, packages/typegpu/src/data/wgslTypes.ts, packages/typegpu/tests/invariant.test.ts
Implements `@invariant` attribute support.
=> feat: invariant attribute

packages/unplugin-typegpu/src/common.ts, packages/unplugin-typegpu/test/regex.test.ts
=> fix: Better regex that includes potential query parameters

packages/typegpu/src/core/pipeline/connectAttachmentToShader.ts, packages/typegpu/src/core/pipeline/connectTargetsToShader.ts, packages/typegpu/tests/renderPipeline.test.ts
=>  fix: not filtering builtin outputs out of the fragment shader
