software-mansion/TypeGPU

- apps/typegpu-docs/src/components/ExampleView.tsx
- apps/typegpu-docs/src/components/design/Button.tsx
- apps/typegpu-docs/src/content/examples/simulation/boids-typedbuffers.ts
- apps/typegpu-docs/src/utils/examples/exampleRunner.ts
closes #314 
\+ created a new non-accented variant for buttons in example controls
\+ added automatic device cleanup for examples, without the need to define onCleanup
> Copy over Boids phase 1 example

- apps/typegpu-docs/package.json
- packages/typegpu/src/resolutionCtx.ts
- packages/typegpu/src/types.ts
This implementation should hopefully be more performant, and prepares for the existence of new layers (function ctx layers for TGSL, etc.)
> impr: ResolutionCtx refactor

- apps/typegpu-docs/src/components/ExampleView.tsx
> Fix mobile preview positioning

- packages/tgpu-cli/package.json
- packages/tgpu-cli/tgpu-cli.mjs
- pnpm-lock.yaml
closes #394 
How it works:
- you can pass in glob pattern as input, generator will be run for each matched file
- example: `npx tgpu-cli gen -i "**/*.wgsl"`
- quotes around pattern are important, so that shell doesn't match a file before passing the argument
- when output is provided, there can only be a single file matched, then the output name is used
- if output is not provided, the pattern has to end with `.wgsl`, the names of the output files will have `.wgsl` replaced with `.ts`
> Make tgpu-cli generator accept glob pattern

- apps/typegpu-docs/src/components/ExampleView.tsx
Link to blog instead of the FAQ.
\+ some visual adjustments and fixes
Before | After
<div class="flex">
</div>
> Link to blog on GPUUnsupportedPanel

- packages/typegpu/src/bindGroupResolver.ts
- packages/typegpu/src/core/buffer/buffer.ts
- packages/typegpu/src/createRoot.ts
- packages/typegpu/src/programBuilder.ts
- packages/typegpu/src/tgpuRoot.ts
- packages/typegpu/tests/bindGroupLayout.test.ts
This is in preparation for exporting the root with limited functionality.
> chore: Split standard and experimental root API.

- apps/typegpu-docs/src/pages/index.astro
before: <img width="400px" src="https://github.com/user-attachments/assets/10f38613-df0e-4fc4-9b48-e4f745fd2930">
> Fix overflow in the roadmap section of the landing page

- packages/tgpu-gen/gen.mjs
- packages/tgpu-gen/tests/functions.test.ts
closes #518 
adds d.location attribute to annotated function argument and return types, as well as to struct members
> Add `d.location` attribute support in tgpu-gen

- packages/tgpu-gen/gen.mjs
- packages/tgpu-gen/tests/functions.test.ts
closes #531 
(note: builtin arguments are still present as struct members)
> Remove builtins from entry function arguments in tgpu-gen

- packages/typegpu/src/tgpuBindGroupLayout.ts
closes #523 
* doesn't do anything yet
* isn't generated by tgpu-gen (also yet)
> Add `$idx` builder method to bindGroupLayouts

- apps/typegpu-docs/src/content/examples/algorithms/mnist-inference/index.ts
`NodeListOf` type does not have an iterator in the live examples environment, this PR changes bars to `Array` type so it can be iterated over inside for..of (according to the types)
> Fix MNIST example type issue

- apps/typegpu-docs/src/content/examples/algorithms/mnist-inference/index.ts
Since there is no event listener for `touchend` there sometimes occurs unwanted interpolation. Simply adding the listener fixes it.
> Fix MNIST inference example bug on mobile

- apps/typegpu-docs/src/components/design/Snackbar.tsx
- apps/typegpu-docs/src/content/docs/blog/troubleshooting.md
- apps/typegpu-docs/src/utils/isGPUSupported.ts
closes #342 
I believe the issue of the gpu adapter being null not at first, but after switching examples was fixed in #556 
I tested our examples page on a couple Android devices, it either worked always, or never.
On one device that it didn't work on initially, I was able to update the Chrome app and it started working after the update, so I believe the issue is not on our part. In this PR I just made it more clear to the user, that their browser doesn't support GPU.
\+ fixed error snackbar size and improved positioning
> Improve null GPU adapter experience on Live Examples page

- packages/typegpu/src/data/numeric.ts
- packages/typegpu/src/data/std140.ts
- packages/typegpu/src/data/vector.ts
> Remove `expressionCode` property from vectors, numerics and bools

- apps/typegpu-docs/src/content/examples/simple/increment-tgsl/index.ts
- apps/typegpu-docs/src/content/examples/simulation/boids-next/index.ts
- apps/typegpu-docs/src/content/examples/simulation/fluid-double-buffering/index.ts
- packages/typegpu/src/core/buffer/bufferUsage.ts
- packages/typegpu/src/core/function/tgpuComputeFn.ts
- packages/typegpu/src/core/function/tgpuFn.ts
- packages/typegpu/src/core/pipeline/computePipeline.ts
- packages/typegpu/src/core/pipeline/renderPipeline.ts
- packages/typegpu/src/core/root/init.ts
- packages/typegpu/src/core/root/rootTypes.ts
- packages/typegpu/src/data/array.ts
- packages/typegpu/src/data/atomic.ts
- packages/typegpu/src/data/attributes.ts
- packages/typegpu/src/data/matrix.ts
- packages/typegpu/src/data/numeric.ts
- packages/typegpu/src/data/std140.ts
- packages/typegpu/src/data/struct.ts
- packages/typegpu/src/data/vector.ts
- packages/typegpu/src/data/vertexFormatData.ts
- packages/typegpu/src/repr.ts
- packages/typegpu/src/tgpuSlot.ts
- packages/typegpu/src/types.ts
- packages/typegpu/tests/bufferUsage.test.ts
- packages/typegpu/tests/computePipeline.test.ts
- `withPrimitive()` on render pipelines,
- `with()` on root to allow for slot bindings,
- Migrated fluid double buffering to new pipelines.
- A new `Infer<T>` type for "parsing", and a "__repr" type token to replace "__unwrapped"
- Making slot.value **double infer**.
Changing "Parsed" to "Infer": https://github.com/software-mansion/TypeGPU/discussions/580
Making slot.value **double infer**: https://github.com/software-mansion/TypeGPU/discussions/586
> Slot bindings on new pipelines.

- apps/typegpu-docs/src/content/examples/algorithms/matrix-multiplication/index.ts
- apps/typegpu-docs/src/content/examples/image-processing/blur/index.ts
- apps/typegpu-docs/src/content/examples/image-processing/camera-thresholding/index.ts
- apps/typegpu-docs/src/content/examples/image-processing/chroma-keying/index.ts
- apps/typegpu-docs/src/content/examples/rendering/box-raytracing/index.ts
- apps/typegpu-docs/src/content/examples/simple/increment/index.ts
- apps/typegpu-docs/src/content/examples/simulation/boids-next/index.ts
- apps/typegpu-docs/src/content/examples/simulation/game-of-life/index.ts
- packages/typegpu/src/core/root/init.ts
- packages/typegpu/src/core/root/rootTypes.ts
- packages/typegpu/src/tgpuBindGroupLayout.ts
- packages/typegpu/tests/bindGroupLayout.test.ts
> `root.createBindGroup` API replacing `layout.populate`

- apps/typegpu-docs/src/content/examples/algorithms/mnist-inference/index.ts
- apps/typegpu-docs/src/content/examples/simulation/boids/index.ts
- packages/typegpu/src/experimental/index.ts
- packages/typegpu/src/resolutionCtx.ts
- packages/typegpu/src/tgpuBindGroupLayout.ts
> Deprecate `populate` method on bindGroupLayout

- packages/typegpu/src/tgpuBindGroupLayout.ts
When missing the proper usage in texture we are getting a misleading error message. Fixed by swapping the order of intersection type.
Before:
After:
> Fix misleading error message when texture validation fails due to missing usage.

- apps/typegpu-docs/src/content/docs/fundamentals/buffers.mdx
closes #639 
> [!CAUTION]
> currently it is not possible to add the `MAP_READ` or `MAP_WRITE` flags, because we include both `COPY_DST` and `COPY_SRC` by default every time. is that okay and we just add info to docs or should we fix this?
> docs: Add info about `$addFlags` method to buffer docs

- packages/typegpu/src/data/attributes.ts
- packages/typegpu/src/data/index.ts
- packages/typegpu/src/data/wgslTypes.ts
- packages/typegpu/tests/interpolate.test.ts
I tried making it as typesafe as I can, by preventing usage of `perspective` or `linear` with integer types. We could also not handle this to simplify the code a bit. Let me know what you prefer.
Example usage:
```typescript
const Data = d.struct({
a: d.f32, // has implicit 'perspective, center' interpolation
b: d.interpolate('linear, sample', d.f32),
});
```
The only unsafe thing I see potentially is that this attribute [must](https://www.w3.org/TR/WGSL/#interpolate-attr) be defined together with `@location`:
```
Must only be applied to a declaration that has a location attribute applied.
```
I didn't know how to enforce this.
I also considered using `['perspective', 'sample']` approach, but typescript would not narrow down after writing `['perspective', ...]`. Then I considered an …
> Add @interpolate attribute

- packages/typegpu/src/core/buffer/bufferUsage.ts
- packages/typegpu/src/core/constant/tgpuConstant.ts
- packages/typegpu/src/core/declare/tgpuDeclare.ts
- packages/typegpu/src/core/function/tgpuComputeFn.ts
- packages/typegpu/src/core/function/tgpuFn.ts
- packages/typegpu/src/core/function/tgpuFragmentFn.ts
- packages/typegpu/src/core/function/tgpuVertexFn.ts
- packages/typegpu/src/core/pipeline/computePipeline.ts
- packages/typegpu/src/core/pipeline/renderPipeline.ts
- packages/typegpu/src/core/resolve/externals.ts
- packages/typegpu/src/core/resolve/tgpuResolve.ts
- packages/typegpu/src/core/root/init.ts
- packages/typegpu/src/core/root/rootTypes.ts
- packages/typegpu/src/core/sampler/sampler.ts
- packages/typegpu/src/core/slot/accessor.ts
- packages/typegpu/src/core/slot/slotTypes.ts
- packages/typegpu/src/core/texture/externalTexture.ts
- packages/typegpu/src/core/texture/texture.ts
- packages/typegpu/src/core/variable/tgpuVariable.ts
- packages/typegpu/src/core/vertexLayout/vertexLayout.ts
- packages/typegpu/src/data/matrix.ts
- packages/typegpu/src/data/vector.ts
- packages/typegpu/src/data/wgslTypes.ts
- packages/typegpu/src/resolutionCtx.ts
- packages/typegpu/src/types.ts
- packages/typegpu/tests/accessor.test.ts
- packages/typegpu/tests/matrix.test.ts
- packages/typegpu/tests/resolve.test.ts
- packages/typegpu/tests/slot.test.ts
Since we have objects that are resolved by an external mechanism (resolveData for schemas) and objects that can resolve themselves (fns, vector and matrix instances, slots, ...), the `resolve` method seems more and more like an internal API.
- Makes the `resolve` method hidden from the public API,
- Alters the type we accept as externals in `tgpu.resolve`
- (BONUS) Makes matrix instances resolvable
> chore: Hide internal resolve API

- apps/typegpu-docs/package.json
- apps/typegpu-docs/src/components/design/DeleteIcon.tsx
- apps/typegpu-docs/src/layouts/PageLayout.astro
- apps/typegpu-docs/src/pages/benchmark/atom-with-url.ts
- apps/typegpu-docs/src/pages/benchmark/benchmark-app.tsx
- apps/typegpu-docs/src/pages/benchmark/index.astro
- apps/typegpu-docs/src/pages/benchmark/modules.ts
- apps/typegpu-docs/src/pages/benchmark/parameter-set-row.tsx
- apps/typegpu-docs/src/pages/benchmark/parameter-set.ts
- apps/typegpu-docs/tailwind.config.mjs
- pnpm-lock.yaml
As we're focusing more and more on performance, I thought a tool for comparing different versions of TypeGPU in the same benchmarks would be a nice tool to have.
Leveraging [esm.sh](https://esm.sh), we can download and run any version of TypeGPU that exists on npm. They also promise that installing packages from PRs should work fine as well, which we could use to:
- Allow a "PR" type of version, synced to the URL like the rest of the state.
- Create a GitHub bot that comments on new PRs with a link to the benchmark, with the id of that PR.
This would allow us to see the performance impact of a PR's changes without having to checkout that code locally 🚀
- Creates a new route in the docs site: `docs.swmansion.com/TypeGPU/benchmark`
- Adds two benchmarks that measure the speed of writing to …
> 🐎: Scaffolding for a benchmarking tool

- packages/unplugin-typegpu/src/babel.ts
This makes it work for cases where `.does()` was already transformed, e.g., for libraries using TypeGPU. This also works with `.does` method calls that don't originate from TypeGPU.
> fix: Make babel plugin target only calls to does with a function expression inside

- packages/typegpu/scripts/generateSwizzleFunctions.ts
- packages/typegpu/src/data/matrix.ts
- packages/typegpu/src/data/vector.ts
- packages/typegpu/src/data/vectorImpl.ts
- packages/typegpu/src/data/vectorOps.ts
- packages/typegpu/src/data/wgslTypes.ts
- packages/typegpu/src/std/numeric.ts
Instead of using `Proxy` to implement swizzling, we can use `new Function` to compile small getters with no runtime if / switch. This should allow js engines to optimize these calls better, but more testing is needed. The most important thing is that `vec[0]` and `vec.x` are simple index access and a getter respectively.
Example swizzle getter:
```
get xxyw() {
return new this._Vec4(this[0], this[0], this[1], this[3]);
}
```
One important change is the ability to unpack vectors like:
```
const [x, y] = v2
```
I achieve this by extending `Array`. Typescript doesn't understand yet that this is possible, but I think we should be able to tell it.
My first tests show almost 2x speedup in `buffer.write` speed, 25ms vs 40ms for 50k `Circle(position, radius, styleIndex)` structs.
> refactor: Vector implementation without using Proxy

- apps/typegpu-docs/src/content/examples/rendering/function-visualizer/index.ts
I think this example will benefit much from it as smooth lines are prone to aliasing
Before:
After:
> Add multisampling to function visualizer

- packages/rollup-plugin/package.json
- packages/tgpu-jit/package.json
- packages/tgpu-wgsl-parser/package.json
- packages/tinyest-for-wgsl/package.json
- packages/tinyest/package.json
- packages/typegpu/package.json
- packages/unplugin-typegpu/package.json
`publishConfig.directory` was causing pnpm to link all libraries to that directory, something I had to fix manually each time a dependency changed. This change fixes that.
> chore: Linking from source directory in local dev

- apps/typegpu-docs/src/content/docs/fundamentals/bind-groups.mdx
- apps/typegpu-docs/src/content/docs/fundamentals/buffers.mdx
- apps/typegpu-docs/src/content/docs/integration/webgpu-interoperability.mdx
- apps/typegpu-docs/src/content/examples/algorithms/mnist-inference/index.ts
- packages/typegpu/src/core/buffer/buffer.ts
- packages/typegpu/src/core/buffer/bufferUsage.ts
- packages/typegpu/src/core/pipeline/renderPipeline.ts
- packages/typegpu/src/core/root/init.ts
- packages/typegpu/src/core/root/rootTypes.ts
- packages/typegpu/src/core/texture/usageExtension.ts
- packages/typegpu/src/extension.ts
- packages/typegpu/src/index.ts
- packages/typegpu/src/tgpuBindGroupLayout.ts
Closes #899 
- Add UniformFlag, StorageFlag and VertexFlag interfaces.
- Deprecate Uniform, Storage and Vertex interfaces.
<details>
<summary>Example code for testing:</summary>
```javascript
import * as d from 'typegpu/data';
import tgpu, {
type TgpuBuffer,
type Storage,
type StorageFlag,
type Uniform,
type UniformFlag,
type Vertex,
type VertexFlag,
} from 'typegpu';
const root = await tgpu.init();
const storageBuffer1: TgpuBuffer<d.Vec2f> & Storage = root
.createBuffer(d.vec2f)
.$usage('storage');
const storageBuffer2: TgpuBuffer<d.Vec2f> & StorageFlag = root
.createBuffer(d.vec2f)
.$usage('storage');
const uniformBuffer1: TgpuBuffer<d.Vec2f> & Uniform = root
.createBuffer(d.vec2f)
.$usage('uniform');
const uniformBuffer2: TgpuBuffer<d.Vec2f> & UniformFlag = root
.createBuffer(d.vec2f) …
```
> chore: Deprecate and rename extension types to avoid ambiguity

- packages/typegpu/src/data/compiledIO.ts
- packages/typegpu/tests/buffer.test.ts
> fix: Handle decorated data in compiledIO and add some tests

- apps/infra-benchmarks/package.json
- apps/infra-benchmarks/src/discriminated-union.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
- tsconfig.base.json
For benchmarking TypeGPU things that can be ran outside of the browser.
- Bump to typescript
- Bump to vitest
> chore: Infra benchmarks boilerplate

- apps/typegpu-docs/src/content/examples/rendering/3d-fish/compute.ts
- apps/typegpu-docs/src/content/examples/rendering/3d-fish/render.ts
- apps/typegpu-docs/src/content/examples/rendering/box-raytracing/index.ts
- packages/typegpu/src/core/resolve/externals.ts
- packages/typegpu/src/tgpuBindGroupLayout.ts
To avoid double "unwrapping" of the layout entries, e.g., `layout.bound.foo.value`.
> feat: layout.value

- packages/tgpu-jit/package.json
- packages/tinyest-for-wgsl/package.json
- packages/tinyest/jsr.json
- packages/tinyest/package.json
- packages/typegpu/package.json
- packages/unplugin-typegpu/package.json
- pnpm-lock.yaml
> [!CAUTION]  
> This version of the plugin requires the newest version of typegpu, which is not yet released.
> bump: typegpu v0.5.4, unplugin-typegpu v0.1.0-alpha.8, tinyest, tinyest-for-wgsl

- packages/unplugin-typegpu/package.json
- pnpm-lock.yaml
> chore: Add `typegpu` as peer dependency of `unplugin-typegpu`

- apps/typegpu-docs/src/layouts/PageLayout.astro
- apps/typegpu-docs/src/pages/benchmark/index.astro
- apps/typegpu-docs/src/pages/examples/index.astro
- apps/typegpu-docs/src/pages/index.astro
This is to improve the look of typegpu.com in searches
**Before:**
**After:**
> docs: Better meta title

- apps/typegpu-docs/src/components/ControlPanel.tsx
- apps/typegpu-docs/src/components/design/ColorPicker.tsx
- apps/typegpu-docs/src/components/design/Select.tsx
- apps/typegpu-docs/src/components/design/Slider.tsx
- apps/typegpu-docs/src/components/design/TextArea.tsx
- apps/typegpu-docs/src/components/design/VectorSlider.tsx
- apps/typegpu-docs/src/components/stackblitz/stackBlitzIndex.ts
- apps/typegpu-docs/src/content/examples/rendering/cubemap-reflection/index.ts
- apps/typegpu-docs/src/layouts/PageLayout.astro
- apps/typegpu-docs/src/utils/examples/exampleControlAtom.ts
- apps/typegpu-docs/src/utils/examples/exampleRunner.ts
> docs: ColorPicker example controls

- apps/typegpu-docs/src/pages/benchmark/modules.ts
The symbol tag for structs was bundled into two different files and therefore some checks on equality with that symbol were failing.
> fix: "Cannot determine size" error in Benchmarks

- packages/typegpu-noise/src/perlin-3d/dynamic-cache.ts
> fix: Perlin noise dynamic cache on Safari

- apps/typegpu-docs/src/content/examples/rendering/perlin-noise/index.ts
- apps/typegpu-docs/src/content/examples/simulation/stable-fluid/index.ts
- packages/typegpu-noise/src/generator.ts
- packages/typegpu-noise/src/perlin-3d/dynamic-cache.ts
- packages/typegpu-noise/src/perlin-3d/static-cache.ts
- packages/typegpu-noise/src/random.ts
- packages/typegpu/setupVitest.ts
- packages/typegpu/src/core/function/fnTypes.ts
- packages/typegpu/src/core/function/tgpuFn.ts
- packages/typegpu/src/core/root/init.ts
- packages/typegpu/src/core/root/rootTypes.ts
- packages/typegpu/src/core/slot/accessor.ts
- packages/typegpu/src/core/slot/slotTypes.ts
- packages/typegpu/src/types.ts
- packages/typegpu/tests/function.test.ts
- packages/typegpu/tests/tgslFn.test.ts
Changes:
- Argument names are maintained by the type system (if implemented using TGSL)
- `TgpuFn` without generic instantiation is wide-enough that it represents any function created using `tgpu.fn`
https://github.com/user-attachments/assets/3f79bf10-9d03-4564-8d05-35dd6f5e7248
> feat: Better TgpuFn type (0.6.0)

- packages/typegpu/src/tgsl/wgslGenerator.ts
- packages/typegpu/tests/tgsl/wgslGenerator.test.ts
This needs to get merged before 0.6.0 as it's a pretty bad bug
> fix: Prevent autocasting lhs of assignment expressions

- apps/typegpu-docs/src/content/docs/reference/data-schema-cheatsheet.mdx
- packages/typegpu/src/core/function/tgpuFn.ts
- packages/typegpu/src/data/struct.ts
- packages/typegpu/src/data/utils.ts
- packages/typegpu/src/data/wgslTypes.ts
- packages/typegpu/src/tgsl/wgslGenerator.ts
- packages/typegpu/tests/struct.test.ts
Structs can now be called with no arguments in order to get a default value of the struct (as long as there are no nested arrays inside).
This is a prerequisite for #1254 (`d.arrayOf(myStruct, 4)()`)
> feat: Struct default constructor

- packages/typegpu/tests/tgslFn.test.ts
- packages/unplugin-typegpu/src/babel.ts
- packages/unplugin-typegpu/src/index.ts
- packages/unplugin-typegpu/test/aliasing.test.ts
- packages/unplugin-typegpu/test/auto-naming.test.ts
- packages/unplugin-typegpu/test/kernel-directive.test.ts
- packages/unplugin-typegpu/test/parser-options.test.ts
- packages/unplugin-typegpu/test/tgsl-transpiling.test.ts
The change allows for a function to reference another function defined later on.
This could potentially lead to people attempting to write recursive functions.
TypeScript screams when either of the following happens (something something _any_):
```ts
const bar = tgpu.fn([], d.f32)(() => foo() + 2);
const foo = tgpu.fn([], d.f32)(() => bar() - 2);
```
```ts
const bar = () => foo() + 2;
const foo = () => bar() - 2;
```
However, the following is fine:
```ts
let bar: TgpuFn; 
let foo: TgpuFn;
bar = tgpu.fn([], d.f32)(() => foo() + 2);
foo = tgpu.fn([], d.f32)(() => bar() - 2);
```
and in this case we get a stack overflow:
```ts
Resolution of the following tree failed: 
- <root>
- fn:bar
- foo: Resolution of the following tree failed: 
- call:foo
- fn:foo
- bar: Resolution of the following …
```
> fix: TypeGPU functions using TGSL dependencies declaration order

- packages/typegpu/src/index.ts
Exporting `TgpuQuerySet` fom tgpu core
> fix: Export `TgpuQuerySet`

- packages/typegpu/src/tgsl/generationHelpers.ts
- packages/typegpu/src/tgsl/wgslGenerator.ts
- packages/typegpu/tests/tgsl/generationHelpers.test.ts
- packages/typegpu/tests/tgsl/wgslGenerator.test.ts
Changes:
- `convertToCommonType` now has an additional parameter, `concretizeTypes`, which makes the function concretize the types before looking for the best conversion
- `generateExpression` now concretizes types when it encounters division
- tests have been updated accordingly
Closes #1551.
> fix: concretize abstract types when performing division

- packages/typegpu/src/std/operators.ts
- packages/typegpu/src/tgsl/generationHelpers.ts
- packages/typegpu/src/tgsl/wgslGenerator.ts
- packages/typegpu/tests/compiledIO.test.ts
- packages/typegpu/tests/struct.test.ts
- packages/typegpu/tests/tgsl/wgslGenerator.test.ts
Currently we are inferring operator result types incorrectly, which causes some examples (e.g., cubemap reflection) to break.
The bug is caused by naively assigning:
```ts
const resultType = isSnippetNumeric(lhs) ? rhs.dataType : lhs.dataType;
```
This breaks as soon as something like:
```
u32(1.5) + 1
```
happens. Here we incorrectly infer this expression to be of type abstractInt.
This PR uses the type conversion system to properly deduce operator return type.
> fix: Unify operand types in arithmetic operators

- apps/typegpu-docs/src/content/examples/algorithms/mnist-inference/index.html
- apps/typegpu-docs/src/content/examples/algorithms/mnist-inference/index.ts
- apps/typegpu-docs/src/content/examples/image-processing/ascii-filter/index.ts
- apps/typegpu-docs/src/content/examples/rendering/3d-fish/index.ts
- apps/typegpu-docs/src/content/examples/rendering/cubemap-reflection/index.ts
- apps/typegpu-docs/src/content/examples/rendering/function-visualizer/index.ts
- apps/typegpu-docs/src/content/examples/rendering/two-boxes/index.ts
- apps/typegpu-docs/src/content/examples/simulation/gravity/index.ts
- apps/typegpu-docs/src/content/examples/simulation/stable-fluid/index.ts
- apps/typegpu-docs/src/content/examples/tests/copy-error/index.ts
Changes:
- cleanup window listeners in all examples (before, some of these tried to write to buffers that were deleted),
- add passive annotations to event listenets,
- remove implicit casts from examples,
- remove logs from Mnist Inference and Struct Copy Test,
- display inference time in Mnist Inference.
To sum up, examples should not throw or log anything when clicking through them (except errors on invalid functions in function visualizer).
> chore: Example logs cleanup

- packages/tinyest-for-wgsl/src/parsers.ts
- packages/tinyest/src/nodes.ts
- packages/typegpu/src/std/numeric.ts
- packages/typegpu/src/tgsl/wgslGenerator.ts
- packages/typegpu/tests/tgsl/wgslGenerator.test.ts
JS `**` operator accepts numbers (of course), and WGSL `pow` only accepts floats.
Changes: 
- remove exception throw on `**` use,
- parse `**` to pow, with forced cast to f32/f16,
- add exception throw on `**=` use.
Let me know what you think about the `**=` operator. I think the following transpilation may be a little too drastic, and I don't think the operator is all that useful.
```ts
// TGSL
let a = d.u32(2);
a **= 4;
```
```wgsl
// WGSL
let a = 2u;
a = u32(pow(f32(a), 4f));
```
> feat: Add support for ** operator

- packages/typegpu/package.json
- packages/typegpu/tests/accessor.test.ts
- packages/typegpu/tests/bindGroupLayout.test.ts
- packages/typegpu/tests/bufferUsage.test.ts
- packages/typegpu/tests/computePipeline.test.ts
- packages/typegpu/tests/declare.test.ts
- packages/typegpu/tests/derived.test.ts
- packages/typegpu/tests/entryFnHeaderGen.test.ts
- packages/typegpu/tests/function.test.ts
- packages/typegpu/tests/functionTagged.test.ts
- packages/typegpu/tests/rawFn.test.ts
- packages/typegpu/tests/renderPipeline.test.ts
- packages/typegpu/tests/resolve.test.ts
- packages/typegpu/tests/slot.test.ts
- packages/typegpu/tests/std/matrix/rotate.test.ts
- packages/typegpu/tests/std/matrix/scale.test.ts
- packages/typegpu/tests/std/matrix/translate.test.ts
- packages/typegpu/tests/std/numeric/mod.test.ts
- packages/typegpu/tests/struct.test.ts
- packages/typegpu/tests/tgsl/codeGen.test.ts
- packages/typegpu/tests/tgsl/infixOperators.test.ts
- packages/typegpu/tests/tgsl/wgslGenerator.test.ts
- packages/typegpu/tests/utils/parseResolved.ts
- packages/typegpu/tests/variable.test.ts
- packages/typegpu/tests/vector.test.ts
- pnpm-lock.yaml
Why?
- Easier to update expected output when a part of how shaders are generated changes
- We can track the visual quality of the produced WGSL code
> chore: Simplify tests using inline snapshots
